{% set name = 'lava' %}
{% set version = '1.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: KernSmooth, Matrix, Rgraphviz, ascii, data.table, fields, foreach, geepack, gof (>= 0.9), graph, igraph (>= 0.6), lava.tobit, lme4, mets (>= 1.1), optimx, quantreg, rgl, testthat (>= 0.11), visNetwork, zoo
requirements:
  build:
    - r-base
    - r-numderiv
    - r-survival

  run:
    - r-base
    - r-numderiv
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lava')"  # [not win]
    - "\"%R%\" -e \"library('lava')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/kkholst/lava
  license: GPL-3
  summary: Estimation and simulation of latent variable models.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: lava
# Type: Package
# Title: Latent Variable Models
# Version: 1.5
# Date: 2017-03-16
# Authors@R: c(person("Klaus K.", "Holst", email="klaus@holst.it", role=c("aut", "cre")), person("Brice", "Ozenne", role = "ctb"), person("Thomas", "Gerds", role = "ctb"))
# Author: Klaus K. Holst [aut, cre], Brice Ozenne [ctb], Thomas Gerds [ctb]
# Maintainer: Klaus K. Holst <klaus@holst.it>
# Description: Estimation and simulation of latent variable models.
# URL: https://github.com/kkholst/lava
# BugReports: https://github.com/kkholst/lava/issues
# License: GPL-3
# LazyLoad: yes
# Depends: R (>= 3.0)
# Imports: grDevices, graphics, methods, numDeriv, stats, survival, utils
# Suggests: KernSmooth, Matrix, Rgraphviz, ascii, data.table, fields, foreach, geepack, gof (>= 0.9), graph, igraph (>= 0.6), lava.tobit, lme4, mets (>= 1.1), optimx, quantreg, rgl, testthat (>= 0.11), visNetwork, zoo
# ByteCompile: yes
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-03-16 20:59:37 UTC; klaus
# Repository: CRAN
# Date/Publication: 2017-03-16 22:51:43 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
