# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /home/rakhan/conda-julia/nettle, last modified Sat May 27 22:13:18 2017
# ------------------------------------------------

package:
    name: nettle
    version: 2.7.1
source:
    fn: nettle-2.7.1.tar.gz
    sha256: bc71ebd43435537d767799e414fce88e521b7278d48c860651216e1fc6555b40
    url: https://ftp.gnu.org/gnu/nettle/nettle-2.7.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    string: '0'
requirements:
    build: []
    run: []
about:
    home: https://www.lysator.liu.se/~nisse/nettle/
    license_file: COPYING.LIB
extra:
    final: true
