# This file created by conda-build 2.1.10
# meta.yaml template originally from:
# /home/conda/conda_recipes/r-geosphere, last modified Thu Apr 27 13:05:31 2017
# ------------------------------------------------

package:
    name: r-geosphere
    version: '1.5_5'
source:
    fn: geosphere_1.5-5.tar.gz
    sha256: 8b6fe012744fc45b88e0ef6f20e60e103ef013e761e99dcff3f9dceeedbdce6d
    url:
        - https://cran.r-project.org/src/contrib/geosphere_1.5-5.tar.gz
        - https://cran.r-project.org/src/contrib/Archive/geosphere/geosphere_1.5-5.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    rpaths:
        - lib/R/lib/
        - lib/
    string: r3.3.2_0
requirements:
    build:
        - zlib 1.2.8 3
        - curl 7.52.1 0
        - gcc 4.8.5 7
        - openssl 1.0.2k 1
        - r-base 3.3.2 1
        - ncurses 5.9 10
        - fontconfig 2.12.1 3
        - libiconv 1.14 0
        - mpfr 3.1.5 0
        - r-sp 1.2_3 r3.3.2_0
        - gsl 2.2.1 0
        - jpeg 9b 0
        - cloog 0.18.0 0
        - xz 5.2.2 1
        - tk 8.5.18 0
        - gmp 6.1.0 0
        - libpng 1.6.27 0
        - isl 0.12.2 0
        - libxml2 2.9.4 0
        - readline 6.2 2
        - glib 2.50.2 1
        - r-lattice 0.20_34 r3.3.2_0
        - freetype 2.5.5 2
        - pango 1.40.3 1
        - icu 54.1 0
        - mpc 1.0.3 0
        - cairo 1.14.8 0
        - libtiff 4.0.6 3
        - harfbuzz 0.9.39 2
        - libffi 3.2.1 1
        - pixman 0.34.0 0
        - libgcc 5.2.0 0
        - pcre 8.39 1
        - jbig 2.1 0
        - bzip2 1.0.6 3
    run:
        - r-base
        - r-sp
test:
    commands:
        - $R -e "library('geosphere')"
about:
    home: https://CRAN.R-project.org/package=geosphere
    license: GPL (>= 3)
    license_family: GPL3
    summary: 'Spherical trigonometry for geographic applications. That is, compute
        distances and related measures for angular (longitude/latitude) locations. '
extra:
    final: true
