package:
  name: theano
  version: "0.9.0"

source:
  fn: Theano-0.9.0.tar.gz
  url: https://pypi.python.org/packages/28/03/6af9ff242da966f89de6ab81164db0d1a36fd89379b7370f07043de62f10/Theano-0.9.0.tar.gz
  md5: 2df1b85fe634b7d9241721b2966e6ae2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - theano = theano:main
    #
    # Would create an entry point called theano that calls theano.main()

    - theano-cache = bin.theano_cache:main
    - theano-nose = bin.theano_nose:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
    - nose
    
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
    - nose
    
test:
  # Python imports
  imports:
    - bin
    - theano
    - theano.compat
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.d3viz
    - theano.d3viz.tests
    - theano.gof
    - theano.gof.tests
    - theano.gpuarray
    - theano.gpuarray.tests
    - theano.misc
    - theano.misc.tests
    - theano.sandbox
    - theano.sandbox.cuda
    - theano.sandbox.cuda.tests
    - theano.sandbox.gpuarray
    - theano.sandbox.linalg
    - theano.sandbox.linalg.tests
    - theano.sandbox.tests
    - theano.scalar
    - theano.scalar.tests
    - theano.scan_module
    - theano.scan_module.tests
    - theano.sparse
    - theano.sparse.sandbox
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests
    - theano.typed_list
    - theano.typed_list.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - theano-cache help
    - theano-nose --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://deeplearning.net/software/theano/
  license: BSD License
  summary: 'Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
