{% set name = 'SuppDists' %}
{% set version = '1.1-9.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SuppDists')"  # [not win]
    - "\"%R%\" -e \"library('SuppDists')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: no longer valid
  license: GPL (>= 2)
  summary: Ten distributions supplementing those built into R. Inverse Gauss, Kruskal-Wallis,
    Kendall's Tau, Friedman's chi squared, Spearman's rho, maximum F ratio, the Pearson
    product moment correlation coefficient, Johnson distributions, normal scores and
    generalized hypergeometric distributions. In addition two random number generators
    of George Marsaglia are included.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: SuppDists
# Version: 1.1-9.4
# Date: 2009-12-09
# Title: Supplementary Distributions
# Author: Bob Wheeler <bwheelerg@gmail.com>
# Maintainer: ORPHANED
# Description: Ten distributions supplementing those built into R. Inverse Gauss, Kruskal-Wallis, Kendall's Tau, Friedman's chi squared, Spearman's rho, maximum F ratio, the Pearson product moment correlation coefficient, Johnson distributions, normal scores and generalized hypergeometric distributions. In addition two random number generators of George Marsaglia are included.
# License: GPL (>= 2)
# URL: no longer valid
# Depends: R (>= 3.3.0)
# NeedsCompilation: yes
# Packaged: 2016-09-19 09:56:39 UTC; ripley
# X-CRAN-Comment: Orphaned on 2013-03-22: the maintainer is unresponsive.
# Repository: CRAN
# Date/Publication: 2016-09-23 09:21:14

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
