# This file created by conda-build 2.0.11
# meta.yaml template originally from:
# /recipe_root, last modified Thu Dec  1 16:41:23 2016
# ------------------------------------------------

package:
    name: tensorflow
    version: 0.12.0rc0
source:
    fn: tensorflow-0.12.0rc0.tar.gz
    sha256: 13a2cb2ed7a3d5ddde5f07d8b8c095442c06e24fee6f044cd3b7df2eed23f5a2
    url: https://github.com/tensorflow/tensorflow/archive/0.12.0-rc0.tar.gz
build:
    entry_points:
        - tensorboard = tensorflow.tensorboard.tensorboard:main
    number: '0'
    string: py35_0
requirements:
    build: !!python/object/apply:builtins.getattr
        - !!python/object:conda_build.environ.Environment
            _meta: /feedstock_root/build_artefacts/recipe_root_1480611412822/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/conda-meta
            _packages: {}
            path: /feedstock_root/build_artefacts/recipe_root_1480611412822/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
        - package_specs
    run:
        - python
        - numpy >=1.11.0
        - protobuf ==3.1.0
        - six >=1.10.0
test:
    imports:
        - tensorflow
about:
    home: http://tensorflow.org/
    license: Apache 2.0
    summary: TensorFlow helps the tensors flow
extra:
    recipe-maintainers:
        - jjhelmus
        - danielfrg
        - waitingkuo
        - ghego
