{% set name = 'SuperLearner' %}
{% set version = '2.0-22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: arm, bartMachine, biglasso, bigmemory, caret, class, dbarts, devtools, e1071, earth, extraTrees, gam, gbm, genefilter, ggplot2, glmnet, Hmisc, ipred, KernelKnn, kernlab, knitr, lattice, LogicReg, MASS, mda, mlbench, nloptr, nnet, party, polspline, prettydoc, quadprog, randomForest, ranger, RhpcBLASctl, ROCR, rmarkdown, rpart, SIS, speedglm, spls, stepPlr, sva, testthat, xgboost (>= 0.6)
requirements:
  build:
    - r-base
    - r-cvauc
    - r-nnls

  run:
    - r-base
    - r-cvauc
    - r-nnls

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SuperLearner')"  # [not win]
    - "\"%R%\" -e \"library('SuperLearner')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ecpolley/SuperLearner
  license: GPL-3
  summary: Implements the super learner prediction method and contains a library of prediction
    algorithms to be used in the super learner.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: SuperLearner
# Type: Package
# Title: Super Learner Prediction
# Version: 2.0-22
# Date: 2017-07-18
# Authors@R: c(person("Eric", "Polley", email = "polley.eric@mayo.edu", role = c("aut", "cre")), person("Erin", "LeDell", role = c("aut")), person("Chris", "Kennedy", role = c("aut")), person("Sam", "Lendle", role = c("ctb")), person("Mark", "van der Laan", role = c("aut", "ths")))
# Maintainer: Eric Polley <polley.eric@mayo.edu>
# Description: Implements the super learner prediction method and contains a library of prediction algorithms to be used in the super learner.
# License: GPL-3
# URL: https://github.com/ecpolley/SuperLearner
# Depends: R (>= 2.14.0), nnls
# Imports: cvAUC
# Suggests: arm, bartMachine, biglasso, bigmemory, caret, class, dbarts, devtools, e1071, earth, extraTrees, gam, gbm, genefilter, ggplot2, glmnet, Hmisc, ipred, KernelKnn, kernlab, knitr, lattice, LogicReg, MASS, mda, mlbench, nloptr, nnet, party, polspline, prettydoc, quadprog, randomForest, ranger, RhpcBLASctl, ROCR, rmarkdown, rpart, SIS, speedglm, spls, stepPlr, sva, testthat, xgboost (>= 0.6)
# LazyLoad: yes
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-07-18 20:35:56 UTC; mri5365
# Author: Eric Polley [aut, cre], Erin LeDell [aut], Chris Kennedy [aut], Sam Lendle [ctb], Mark van der Laan [aut, ths]
# Repository: CRAN
# Date/Publication: 2017-07-18 22:39:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
