{% set name = 'pander' %}
{% set version = '0.6.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: grid, lattice, ggplot2 (>= 0.9.2), koRpus, futile.logger, survival, microbenchmark, zoo, nlme, descr, MASS, knitr, rmarkdown, tables, reshape, memisc, Epi, randomForest, tseries, gtable, rms, forecast, data.table
requirements:
  build:
    - r-base
    - r-rcpp
    - r-digest
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - r-digest

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pander')"  # [not win]
    - "\"%R%\" -e \"library('pander')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://rapporter.github.io/pander
  license: AGPL-3 | file LICENSE
  summary: 'Contains some functions catching all messages, ''stdout'' and other useful information
    while evaluating R code and other helpers to return user specified text elements
    (like: header, paragraph, table, image, lists etc.) in ''pandoc'' markdown or several
    type of R objects similarly automatically transformed to markdown format. Also capable
    of exporting/converting (the resulting) complex ''pandoc'' documents to e.g. HTML,
    ''PDF'', ''docx'' or ''odt''. This latter reporting feature is supported in brew
    syntax or with a custom reference class with a smarty caching ''backend''.'

  license_family: AGPL

# The original CRAN metadata for this package was:

# Package: pander
# Maintainer: Gergely Darczi <daroczig@rapporter.net>
# Title: An R 'Pandoc' Writer
# Type: Package
# Encoding: UTF-8
# Description: Contains some functions catching all messages, 'stdout' and other useful information while evaluating R code and other helpers to return user specified text elements (like: header, paragraph, table, image, lists etc.) in 'pandoc' markdown or several type of R objects similarly automatically transformed to markdown format. Also capable of exporting/converting (the resulting) complex 'pandoc' documents to e.g. HTML, 'PDF', 'docx' or 'odt'. This latter reporting feature is supported in brew syntax or with a custom reference class with a smarty caching 'backend'.
# Author: Gergely Darczi <daroczig@rapporter.net>, Roman Tsegelskyi <roman.tsegelskyi@gmail.com>
# Version: 0.6.1
# Date: 2017-08-04
# URL: http://rapporter.github.io/pander
# BugReports: https://github.com/rapporter/pander/issues
# License: AGPL-3 | file LICENSE
# Depends: R (>= 2.15.0)
# Imports: grDevices, graphics, methods, utils, stats, digest, tools, Rcpp
# Suggests: grid, lattice, ggplot2 (>= 0.9.2), koRpus, futile.logger, survival, microbenchmark, zoo, nlme, descr, MASS, knitr, rmarkdown, tables, reshape, memisc, Epi, randomForest, tseries, gtable, rms, forecast, data.table
# SystemRequirements: pandoc (http://johnmacfarlane.net/pandoc) for exporting markdown files to other formats.
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-08-06 12:33:36 UTC; daroczig
# Repository: CRAN
# Date/Publication: 2017-08-06 16:21:29 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
