{% set name = 'rmeta' %}
{% set version = '2.16' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rmeta')"  # [not win]
    - "\"%R%\" -e \"library('rmeta')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rmeta
  license: GPL-2
  summary: Functions for simple fixed and random effects meta-analysis for two-sample comparisons
    and cumulative meta-analyses. Draws standard summary plots, funnel plots, and computes
    summaries and tests for association and heterogeneity
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: rmeta
# Version: 2.16
# Author: Thomas Lumley <tlumley@u.washington.edu>
# Maintainer: Thomas Lumley <tlumley@u.washington.edu>
# Description: Functions for simple fixed and random effects meta-analysis for two-sample comparisons and cumulative meta-analyses. Draws standard summary plots, funnel plots, and computes summaries and tests for association and heterogeneity
# Title: Meta-analysis
# License: GPL-2
# Depends: grid
# Packaged: 2012-10-29 08:59:36 UTC; ripley
# Repository: CRAN
# Date/Publication: 2012-10-29 08:59:36
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
