{% set version = '1.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-compquadform
  version: {{ version|replace("-", "_") }}

source:
  fn: CompQuadForm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/CompQuadForm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/CompQuadForm/CompQuadForm_{{ version }}.tar.gz


  sha256: 042fc56c800dd8f5f47a017e2efa832caf74f0602824abf7099898d9708660c4
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - gcc                  # [not win]

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('CompQuadForm')"  # [not win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=CompQuadForm
  license: GPL (>= 2)
  summary: Computes the distribution function of quadratic forms in normal variables using Imhof's
    method, Davies's algorithm, Farebrother's algorithm or Liu et al.'s algorithm.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: CompQuadForm
# Type: Package
# Title: Distribution Function of Quadratic Forms in Normal Variables
# Version: 1.4.3
# Date: 2017-04-10
# Author: P. Lafaye de Micheaux
# Maintainer: P. Lafaye de Micheaux <lafaye@unsw.edu.au>
# Description: Computes the distribution function of quadratic forms in normal variables using Imhof's method, Davies's algorithm, Farebrother's algorithm or Liu et al.'s algorithm.
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2017-04-10 02:26:43 UTC; lafaye
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2017-04-12 14:28:23 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
