{% set name = 'epiR' %}
{% set version = '0.9-87' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS (>= 3.1-20)
requirements:
  build:
    - r-base
    - r-biasedurn
    - r-survival

  run:
    - r-base
    - r-biasedurn
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('epiR')"  # [not win]
    - "\"%R%\" -e \"library('epiR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://fvas.unimelb.edu.au/veam
  license: GPL (>= 2)
  summary: Tools for the analysis of epidemiological data. Contains functions for directly and
    indirectly adjusting measures of disease frequency, quantifying measures of association
    on the basis of single or multiple strata of count data presented in a contingency
    table, and computing confidence intervals around incidence risk and incidence rate
    estimates. Miscellaneous functions for use in meta-analysis, diagnostic test interpretation,
    and sample size calculations.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: epiR
# Version: 0.9-87
# Date: 2017-06-30
# Title: Tools for the Analysis of Epidemiological Data
# Author: Mark Stevenson <mark.stevenson1@unimelb.edu.au> with contributions from Telmo Nunes, Cord Heuer, Jonathon Marshall, Javier Sanchez, Ron Thornton, Jeno Reiczigel, Jim Robison-Cox, Paola Sebastiani, Peter Solymos, Kazuki Yoshida, Geoff Jones, Sarah Pirikahu, Simon Firestone and Ryan Kyle.
# Maintainer: Mark Stevenson <mark.stevenson1@unimelb.edu.au>
# Description: Tools for the analysis of epidemiological data. Contains functions for directly and indirectly adjusting measures of disease frequency, quantifying measures of association on the basis of single or multiple strata of count data presented in a contingency table, and computing confidence intervals around incidence risk and incidence rate estimates. Miscellaneous functions for use in meta-analysis, diagnostic test interpretation, and sample size calculations.
# Depends: R (>= 3.0.0), survival
# Imports: BiasedUrn, methods
# Suggests: MASS (>= 3.1-20)
# License: GPL (>= 2)
# URL: http://fvas.unimelb.edu.au/veam
# NeedsCompilation: no
# Packaged: 2017-06-30 07:54:55 UTC; Mark
# Repository: CRAN
# Date/Publication: 2017-06-30 22:15:10 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
