{% set name = 'cvAUC' %}
{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-rocr
    - r-data.table

  run:
    - r-base
    - r-rocr
    - r-data.table

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('cvAUC')"  # [not win]
    - "\"%R%\" -e \"library('cvAUC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ledell/cvAUC
  license: Apache License (== 2.0)
  summary: 'This package contains various tools for working with and evaluating cross-validated
    area under the ROC curve (AUC) estimators.  The primary functions of the package
    are ci.cvAUC and ci.pooled.cvAUC, which report cross-validated AUC and compute confidence
    intervals for cross-validated AUC estimates based on influence curves for i.i.d.
    and pooled repeated measures data, respectively.  One benefit to using influence
    curve based confidence intervals is that they require much less computation time
    than bootstrapping methods.  The utility functions, AUC and cvAUC, are simple wrappers
    for functions from the ROCR package. '

  license_family: APACHE

# The original CRAN metadata for this package was:

# Package: cvAUC
# Type: Package
# Title: Cross-Validated Area Under the ROC Curve Confidence Intervals
# Version: 1.1.0
# Date: 2014-12-07
# Author: Erin LeDell, Maya Petersen, Mark van der Laan
# Maintainer: Erin LeDell <ledell@berkeley.edu>
# Description: This package contains various tools for working with and evaluating cross-validated area under the ROC curve (AUC) estimators.  The primary functions of the package are ci.cvAUC and ci.pooled.cvAUC, which report cross-validated AUC and compute confidence intervals for cross-validated AUC estimates based on influence curves for i.i.d. and pooled repeated measures data, respectively.  One benefit to using influence curve based confidence intervals is that they require much less computation time than bootstrapping methods.  The utility functions, AUC and cvAUC, are simple wrappers for functions from the ROCR package.
# License: Apache License (== 2.0)
# Depends: ROCR, data.table
# URL: https://github.com/ledell/cvAUC
# BugReports: https://github.com/ledell/cvAUC/issues
# LazyLoad: yes
# Packaged: 2014-12-09 01:09:45 UTC; ledell
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-12-09 07:12:38

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
