FROM condaforge/linux-anvil

MAINTAINER Jonathan J. Helmus <jjhelmus@gmail.com>

# Install OpenJDK
RUN yum install -y java-1.8.0-openjdk-devel 
RUN yum install -y unzip zip zlib-devel rsync

# Install essential tools
#RUN yum install -y wget unzip git 
#RUN yum install -y zip zlib-devel
