package:
  name: tensorflow
  version: "0.10.0rc0"

source:
  fn: v0.10.0rc0.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v0.10.0rc0.tar.gz
  sha256: df28bbe5470171eb0199905423902a96fe370052f8458a28d40c294c662d614b

build:
  number: 1
  skip: True  # [win]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - swig
    - mock >=2.0.0
    - numpy >=1.8.2
    - protobuf ==3.0.0b2
    - six >=1.10.0
    - wheel
    # bazel is also a build requirement but is being provided by the system
  run:
    - python
    - mock >=2.0.0
    - numpy >=1.8.2
    - protobuf ==3.0.0b2
    - six >=1.10.0

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
