{% set name = 'prodlim' %}
{% set version = '1.6.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('prodlim')"  # [not win]
    - "\"%R%\" -e \"library('prodlim')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=prodlim
  license: GPL (>= 2)
  summary: Fast and user friendly implementation of nonparametric estimators for censored event
    history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: prodlim
# Title: Product-Limit Estimation for Censored Event History Analysis
# Version: 1.6.1
# Author: Thomas A. Gerds
# Description: Fast and user friendly implementation of nonparametric estimators for censored event history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
# Depends: R (>= 2.9.0)
# Imports: Rcpp (>= 0.11.5), stats, graphics, survival, KernSmooth, lava
# LinkingTo: Rcpp
# Maintainer: Thomas A. Gerds <tag@biostat.ku.dk>
# License: GPL (>= 2)
# Packaged: 2017-03-06 12:06:02 UTC; tag
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2017-03-06 13:53:09

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
